version: "3.4"

networks:
  code-network:
    driver: bridge

services:
  php-alpine:
    container_name: php-alpine
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    networks:
      - code-network